server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.skytel.beanhub: DEBUG


jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key


spring:
  application:
    name: beanhub-be
  datasource:
    url: jdbc:postgresql://localhost:5432/beanhub-db
    username: postgres
    password: 123456
  jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true

  flyway:
    enabled: true
